"""
TemporalShield / NexusTrace — Event Stream Producer (Kafka & In-Memory Fallback)

Important — What Kafka Does and Does Not Do:
Kafka does NOT generate any data. It is purely a delivery mechanism — like a postman that reads
your pre-written letters and delivers them one by one at a controlled pace. All data was already
generated by Dnyanesh's Faker scripts and saved as CSV files. Kafka reads those rows and publishes
them in timestamp order, making it feel like events are arriving live during the demo.
Nothing new is created at runtime.

What it does:
- Reads access_logs.csv (63,000+ rows) and synthetic_transactions.csv (7,143 rows) row by row.
- Publishes each row as a live JSON event to two topics simultaneously in timestamp order:
    Topic: access_events
    Topic: transactions
- PaySim is NOT streamed — it was only used for model training. Only synthetic datasets stream
  because they share ACC_XXXXX account IDs.
- Speed multiplier: 500x by default (compresses 30 days of data into ~60 seconds).
- Scenario mode: on-demand instant replay of pre-filtered scenario subsets:
    - temporal_link: scenario == 'temporal_link'
    - structuring: scenario == 'structuring'
    - circular_transfer: scenario == 'circular_transfer'
    - clean_busy: scenario == 'clean_busy'
- Fallback mode: Seamlessly routes to thread-safe in-memory queue if Kafka broker is unavailable.
"""

import os
import json
import time
import logging
import threading
from datetime import datetime
from typing import Dict, Any, List, Optional, Tuple
import pandas as pd

try:
    from data.event_bus import get_queue, clear_all_queues
except ImportError:
    import sys
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from data.event_bus import get_queue, clear_all_queues

logger = logging.getLogger("TemporalShield.KafkaProducer")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

# Default Kafka Configuration
DEFAULT_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
TOPIC_ACCESS = "access_events"
TOPIC_TRANSACTIONS = "transactions"


class StreamProducer:
    """
    Simultaneously reads access logs and synthetic transactions, interleaving them
    in chronological order and publishing to Kafka or the in-memory fallback queue.
    """

    def __init__(
        self,
        bootstrap_servers: str = DEFAULT_BOOTSTRAP_SERVERS,
        use_kafka: bool = False,
        speed_multiplier: float = 500.0,
        access_csv_path: Optional[str] = None,
        txn_csv_path: Optional[str] = None
    ):
        self.bootstrap_servers = bootstrap_servers
        self.use_kafka = use_kafka
        self.speed_multiplier = speed_multiplier
        self.access_csv_path = access_csv_path or self._resolve_data_file("access_logs.csv")
        self.txn_csv_path = txn_csv_path or self._resolve_data_file("synthetic_transactions.csv")

        self.producer = None
        self._init_kafka_producer()

        self._stop_event = threading.Event()
        self._pause_event = threading.Event()
        self._stream_thread: Optional[threading.Thread] = None
        self.events_published_count = 0
        self.current_scenario: Optional[str] = None
        self.is_running = False

    def _resolve_data_file(self, filename: str) -> str:
        base_dir = os.path.dirname(os.path.abspath(__file__))
        cand1 = os.path.join(base_dir, filename)
        if os.path.exists(cand1):
            return cand1
        cand2 = os.path.join(os.path.dirname(base_dir), "data", filename)
        if os.path.exists(cand2):
            return cand2
        return filename

    def _init_kafka_producer(self):
        """Attempts to initialize kafka-python producer; falls back to in-memory queue gracefully."""
        if not self.use_kafka:
            logger.info("KafkaProducer operating in Fallback Mode (In-Memory Queue).")
            return

        try:
            from kafka import KafkaProducer
            self.producer = KafkaProducer(
                bootstrap_servers=self.bootstrap_servers,
                value_serializer=lambda v: json.dumps(v).encode("utf-8"),
                request_timeout_ms=3000,
                max_block_ms=3000
            )
            logger.info(f"Connected to Kafka broker at {self.bootstrap_servers}")
        except Exception as e:
            logger.warning(
                f"Could not connect to Kafka ({e}). Automatically switching to Fallback Mode (In-Memory Queue)."
            )
            self.use_kafka = False
            self.producer = None

    def load_scenario_dataset(self, scenario: Optional[str] = None) -> List[Tuple[pd.Timestamp, str, Dict[str, Any]]]:
        """
        Loads CSV files and merges access logs and transactions into a single
        chronologically ordered list of tuples: (timestamp, topic, payload).
        """
        logger.info(f"Loading datasets (scenario={scenario or 'FULL_TIMELINE'})...")

        # 1. Load Synthetic Transactions
        df_txns = pd.DataFrame()
        if os.path.exists(self.txn_csv_path):
            df_txns = pd.read_csv(self.txn_csv_path)
            df_txns["timestamp"] = pd.to_datetime(df_txns["timestamp"])

            # Filter by scenario if requested
            if scenario and scenario.lower() != "all":
                df_txns = df_txns[df_txns["scenario"].str.lower() == scenario.lower()].copy()
                logger.info(f"Filtered {len(df_txns)} transactions for scenario: {scenario}")
        else:
            logger.error(f"Transaction CSV not found at {self.txn_csv_path}")

        # 2. Load Access Logs
        df_access = pd.DataFrame()
        if os.path.exists(self.access_csv_path):
            df_access = pd.read_csv(self.access_csv_path)
            df_access["timestamp"] = pd.to_datetime(df_access["timestamp"])

            if scenario and scenario.lower() != "all" and not df_txns.empty:
                # In scenario mode, include access logs for relevant accounts and timestamp bounds
                scenario_accounts = set(df_txns["account_id"].unique())
                t_min = df_txns["timestamp"].min() - pd.Timedelta(hours=2)
                t_max = df_txns["timestamp"].max() + pd.Timedelta(hours=2)

                df_access = df_access[
                    (df_access["account_id"].isin(scenario_accounts)) &
                    (df_access["timestamp"] >= t_min) &
                    (df_access["timestamp"] <= t_max)
                ].copy()
                logger.info(f"Selected {len(df_access)} matching access logs for scenario accounts.")
        else:
            logger.error(f"Access log CSV not found at {self.access_csv_path}")

        # 3. Interleave both streams chronologically
        combined_events: List[Tuple[pd.Timestamp, str, Dict[str, Any]]] = []

        for _, row in df_access.iterrows():
            payload = {
                "employee_id": str(row.get("employee_id")),
                "role": str(row.get("role")),
                "account_id": str(row.get("account_id")),
                "account_type": str(row.get("account_type")),
                "branch_code": str(row.get("branch_code")),
                "action_type": str(row.get("action_type")),
                "timestamp": str(row["timestamp"]),
                "records_accessed": int(row.get("records_accessed", 1)),
                "is_suspicious": int(row.get("is_suspicious", 0))
            }
            combined_events.append((row["timestamp"], TOPIC_ACCESS, payload))

        for _, row in df_txns.iterrows():
            payload = {
                "transaction_id": str(row.get("transaction_id")),
                "account_id": str(row.get("account_id")),
                "amount": float(row.get("amount", 0.0)),
                "transaction_type": str(row.get("transaction_type", "TRANSFER")),
                "counterparty_id": str(row.get("counterparty_id", "EXT_UNKNOWN")),
                "timestamp": str(row["timestamp"]),
                "branch_code": str(row.get("branch_code", "BR_001")),
                "is_fraud": int(row.get("is_fraud", 0)),
                "scenario": str(row.get("scenario", "normal"))
            }
            combined_events.append((row["timestamp"], TOPIC_TRANSACTIONS, payload))

        # Sort strictly by timestamp
        combined_events.sort(key=lambda x: x[0])
        logger.info(f"Total merged event stream size: {len(combined_events):,} events.")
        return combined_events

    def publish_event(self, topic: str, payload: Dict[str, Any]):
        """Publishes a single event to Kafka or in-memory queue."""
        if self.use_kafka and self.producer:
            try:
                self.producer.send(topic, payload)
            except Exception as e:
                logger.error(f"Kafka publish error: {e}, falling back to in-memory queue.")
                get_queue(topic).put(payload)
        else:
            get_queue(topic).put(payload)

        self.events_published_count += 1

    def _stream_worker(self, events: List[Tuple[pd.Timestamp, str, Dict[str, Any]]], speed_multiplier: float):
        """Worker thread streaming events with time-compressed delays."""
        self.is_running = True
        logger.info(f"Stream started with {len(events)} events at {speed_multiplier}x speed.")

        for i, (ts, topic, payload) in enumerate(events):
            if self._stop_event.is_set():
                break

            # Handle pause
            while self._pause_event.is_set() and not self._stop_event.is_set():
                time.sleep(0.1)

            # Compute realistic compressed delay between events
            if i > 0 and speed_multiplier > 0:
                prev_ts = events[i - 1][0]
                delta_sec = max(0.0, (ts - prev_ts).total_seconds())
                # Compress 30 days (2,592,000s) down to demo speed
                delay = delta_sec / speed_multiplier
                # Cap max delay to 0.15s so the demo remains responsive
                delay = min(0.15, max(0.001, delay))
                time.sleep(delay)

            self.publish_event(topic, payload)

        self.is_running = False
        logger.info(f"Stream completed. Total published: {self.events_published_count} events.")

    def start_stream(self, scenario: Optional[str] = None, speed_multiplier: Optional[float] = None, async_run: bool = True):
        """Starts streaming events for a given scenario or full timeline."""
        self.stop_stream()
        self._stop_event.clear()
        self._pause_event.clear()
        self.events_published_count = 0
        self.current_scenario = scenario

        speed = speed_multiplier or self.speed_multiplier
        events = self.load_scenario_dataset(scenario=scenario)

        if async_run:
            self._stream_thread = threading.Thread(
                target=self._stream_worker,
                args=(events, speed),
                daemon=True
            )
            self._stream_thread.start()
        else:
            self._stream_worker(events, speed)

    def stop_stream(self):
        """Stops the ongoing stream."""
        self._stop_event.set()
        if self._stream_thread and self._stream_thread.is_alive():
            self._stream_thread.join(timeout=1.0)
        self.is_running = False

    def pause_stream(self):
        """Pauses the stream."""
        self._pause_event.set()

    def resume_stream(self):
        """Resumes the stream."""
        self._pause_event.clear()

    def reset(self):
        """Stops stream and clears event queues."""
        self.stop_stream()
        clear_all_queues()
        self.events_published_count = 0
        self.current_scenario = None


# Quick test
if __name__ == "__main__":
    producer = StreamProducer(use_kafka=False, speed_multiplier=1000.0)
    print("Testing temporal_link scenario streaming...")
    producer.start_stream(scenario="temporal_link", async_run=False)
    print(f"Published {producer.events_published_count} events.")
    acc_q = get_queue(TOPIC_ACCESS)
    txn_q = get_queue(TOPIC_TRANSACTIONS)
    print(f"In-memory queues: access={acc_q.qsize()}, txns={txn_q.qsize()}")
